from arlorobot import *
import utime

bot = ArloRobot()
print("Reseteando encoder...")
bot.clear_counts()
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
bot.move(0, 100, 200)
utime.sleep(4)
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
bot.move(0, 50, 200)
utime.sleep(4)
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
bot.move(0, -150, 200)
utime.sleep(4)
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
bot.move(0, -200, 200)
utime.sleep(4)
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
bot.move(0, -200, 200)
utime.sleep(4)
print("Posiciones efectuadas por motor derecho: ", bot.read_right_counts())
